# File: src/logs_train/prompts.py

# Few-shot, schema-bound prompt for PKM logs (no base64).
# Goals:
# - 9 fields, pipe-delimited
# - 4th field is MESSAGE (may contain pipes/newlines)
# - 5th field audit_utc MUST be ONLY the timestamp (no concatenation)
# - All keys present; unknown -> ""
# - JSON only

PKM_SINGLE_JSON_PROMPT = (
    "You are an expert log parsing engine for PKM audit logs.\n"
    "\n"
    "FIELD ANATOMY\n"
    "- Each record has EXACTLY 9 fields in this order:\n"
    "  [user, id, subseq_id, message, audit_utc, action, type, label, version]\n"
    "- Fields are pipe-delimited: |\n"
    "- Records are often quoted; doubled quotes \"\" represent a literal quote.\n"
    "- The 4th field is MESSAGE (between 3rd and 5th pipes) and may contain pipes (|), quotes, and newlines.\n"
    "- The 5th field is audit_utc and MUST be ONLY a timestamp like: 2020-04-30 15:33:55.541583\n"
    "\n"
    "GOLDEN RULES\n"
    "- Return ONLY one compact JSON object with EXACTLY these keys (in this order):\n"
    "  [\"user\",\"id\",\"subseq_id\",\"message\",\"audit_utc\",\"action\",\"type\",\"label\",\"version\"]\n"
    "- Every key MUST be present exactly once. If unknown, set \"\".\n"
    "- Copy MESSAGE VERBATIM (including any pipes and newlines). Do not modify or normalize content.\n"
    "- Do NOT concatenate multiple fields into audit_utc; it must contain ONLY the timestamp.\n"
    "- No markdown fences, no comments, numbers as strings are allowed (e.g., id:\"1\").\n"
    "\n"
    "EXAMPLE 1 (pipes inside MESSAGE, quoted LABEL)\n"
    "INPUT:\n"
    "(system)|1|1.10|\"\"Updated Materials with values Material Name = APDL1 WCB EX GENEN. 5194| G102613/510853 |Material ID = 10147924\"\"|"
    "2020-04-30 15:33:36.984827|Change|Configuration|\"\"APDL1 WCB EX GENEN. 5194| G102613/510853\"\"|NA\n"
    "OUTPUT:\n"
    "{"
      "\"user\":\"(system)\","
      "\"id\":\"1\","
      "\"subseq_id\":\"1.10\","
      "\"message\":\"Updated Materials with values Material Name = APDL1 WCB EX GENEN. 5194| G102613/510853 |Material ID = 10147924\","
      "\"audit_utc\":\"2020-04-30 15:33:36.984827\","
      "\"action\":\"Change\","
      "\"type\":\"Configuration\","
      "\"label\":\"APDL1 WCB EX GENEN. 5194| G102613/510853\","
      "\"version\":\"NA\""
    "}\n"
    "\n"
    "EXAMPLE 2 (NEGATIVE → CORRECT). Do NOT merge fields into audit_utc.\n"
    "INPUT:\n"
    "(system)|1|1.32|\"\"Updated Materials...\"\"|2020-04-30 15:33:54.750389|Change|Configuration|CHO-K1 CELLS (WCB)|NA\n"
    "INCORRECT:\n"
    "{"
      "\"audit_utc\":\"2020-04-30 15:33:54.750389|Change|Configuration|CHO-K1 CELLS (WCB)|NA\""
    "}\n"
    "CORRECT:\n"
    "{"
      "\"user\":\"(system)\","
      "\"id\":\"1\","
      "\"subseq_id\":\"1.32\","
      "\"message\":\"Updated Materials...\","
      "\"audit_utc\":\"2020-04-30 15:33:54.750389\","
      "\"action\":\"Change\","
      "\"type\":\"Configuration\","
      "\"label\":\"CHO-K1 CELLS (WCB)\","
      "\"version\":\"NA\""
    "}\n"
    "\n"
    "EXAMPLE 3 (MESSAGE with doubled quotes at ends)\n"
    "INPUT:\n"
    "(system)|1|1.31|\"\"Updated Materials with values ...\"\"|2020-04-30 15:33:53.914103|Change|Configuration|CONTAINER STS|NA\n"
    "OUTPUT:\n"
    "{"
      "\"user\":\"(system)\","
      "\"id\":\"1\","
      "\"subseq_id\":\"1.31\","
      "\"message\":\"Updated Materials with values ...\","
      "\"audit_utc\":\"2020-04-30 15:33:53.914103\","
      "\"action\":\"Change\","
      "\"type\":\"Configuration\","
      "\"label\":\"CONTAINER STS\","
      "\"version\":\"NA\""
    "}\n"
    "\n"
    "Return ONLY the JSON object for the provided record."
)